name: Release Drafter
on: 
  push:
    branches:
      - master
      - develop
      - develop8.1

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - name: Get release drafter configuration file name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo release-drafter-${GITHUB_REF#refs/heads/}.yml)"
      id: extract_branch
       
    - name: Print release drafter configuration file name
      run: |
          write-host ${{ steps.extract_branch.outputs.branch }}
      shell: pwsh

    - name: Drafts your next Release notes as Pull Requests are merged
      uses: release-drafter/release-drafter@v5
      with:
        config-name: ${{ steps.extract_branch.outputs.branch }} # located in .github/ in default branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
